code_extensions_map:
  - 'python': [ '.py', '.pyw', '.pyi', '.pyx', '.pxd' ]
  - 'javascript': [ '.js', '.jsx', '.mjs', '.cjs' ]
  - 'typescript': [ '.ts', '.tsx', '.mts', '.cts' ]
  - 'java': [ '.java', '.jar' ]
  - 'csharp': [ '.cs', '.csx' ]
  - 'cpp': [ '.cpp', '.cc', '.cxx', '.c', '.h', '.hpp', '.hxx', '.hh' ]
  - 'ruby': [ '.rb', '.erb', '.rake', '.gemspec' ]
  - 'go': [ '.go' ]
  - 'php': [ '.php', '.phtml', '.php3', '.php4', '.php5' ]
  - 'swift': [ '.swift' ]
  - 'kotlin': [ '.kt', '.kts' ]
  - 'rust': [ '.rs' ]
  - 'html': [ '.html', '.htm', '.xhtml' ]
  - 'css': [ '.css', '.scss', '.sass', '.less', '.styl' ]
  - 'shell': [ '.sh', '.bash', '.zsh', '.fish', '.ksh', '.csh' ]
  - 'json': [ '.json', '.jsonc', '.json5' ]
  - 'yaml': [ '.yaml', '.yml' ]
  - 'xml': [ '.xml', '.xsl', '.xslt', '.svg', '.xaml' ]
  - 'sql': [ '.sql', '.psql', '.plsql' ]
  - 'csv': [ '.csv', '.tsv' ]
  - 'markdown': [ '.md', '.mdx', '.markdown' ]
  - 'scala': [ '.scala', '.sc' ]
  - 'clojure': [ '.clj', '.cljs', '.cljc', '.edn' ]
  - 'haskell': [ '.hs', '.lhs' ]
  - 'elixir': [ '.ex', '.exs' ]
  - 'erlang': [ '.erl', '.hrl' ]
  - 'lua': [ '.lua' ]
  - 'perl': [ '.pl', '.pm', '.pod' ]
  - 'r': [ '.r', '.R', '.rmd' ]
  - 'julia': [ '.jl' ]
  - 'dart': [ '.dart' ]
  - 'vue': [ '.vue' ]
  - 'svelte': [ '.svelte' ]
  - 'graphql': [ '.graphql', '.gql' ]
  - 'protobuf': [ '.proto' ]
  - 'toml': [ '.toml' ]
  - 'ini': [ '.ini', '.cfg', '.conf' ]
  - 'dockerfile': [ 'Dockerfile', '.dockerfile' ]
  - 'makefile': [ 'Makefile', '.mk' ]
  - 'cmake': [ 'CMakeLists.txt', '.cmake' ]
  - 'gradle': [ '.gradle', '.gradle.kts' ]
  - 'terraform': [ '.tf', '.tfvars' ]
  - 'puppet': [ '.pp' ]
  - 'ansible': [ '.ansible' ]
  - 'nginx': [ '.nginx', '.nginxconf' ]
  - 'apache': [ '.htaccess', '.apacheconf' ]
  - 'powershell': [ '.ps1', '.psm1', '.psd1' ]
  - 'batch': [ '.bat', '.cmd' ]
  - 'vim': [ '.vim', '.vimrc' ]
  - 'latex': [ '.tex', '.sty', '.cls', '.bib' ]
  - 'solidity': [ '.sol' ]
  - 'zig': [ '.zig' ]
  - 'nim': [ '.nim' ]
  - 'ocaml': [ '.ml', '.mli' ]
  - 'fsharp': [ '.fs', '.fsi', '.fsx' ]
  - 'assembly': [ '.asm', '.s' ]
  - 'groovy': [ '.groovy', '.gvy' ]
  - 'coffeescript': [ '.coffee' ]
  - 'objective-c': [ '.m', '.mm' ]
  - 'fortran': [ '.f', '.f90', '.f95', '.for' ]
  - 'cobol': [ '.cbl', '.cob', '.cpy' ]
  - 'pascal': [ '.pas', '.pp' ]
  - 'ada': [ '.adb', '.ads' ]
  - 'vhdl': [ '.vhd', '.vhdl' ]
  - 'verilog': [ '.v', '.sv' ]

raw_text_extensions_map:
  - 'text': [ '.txt', '.text' ]
  - 'log': [ '.log' ]
  - 'readme': [ 'README', 'CHANGELOG', 'LICENSE', 'AUTHORS', 'CONTRIBUTORS' ]
  - 'config': [ '.env', '.env.local', '.env.development', '.env.production' ]
  - 'gitignore': [ '.gitignore', '.gitattributes', '.gitmodules' ]
  - 'editorconfig': [ '.editorconfig' ]
  - 'properties': [ '.properties' ]
  - 'ascii': [ '.asc', '.ascii' ]
  - 'restructuredtext': [ '.rst' ]
  - 'asciidoc': [ '.adoc', '.asciidoc' ]
  - 'org': [ '.org' ]

rich_text_extensions_map:
  - 'word': [ '.doc', '.docx', '.docm' ]
  - 'excel': [ '.xls', '.xlsx', '.xlsm', '.xlsb' ]
  - 'powerpoint': [ '.ppt', '.pptx', '.pptm' ]
  - 'pdf': [ '.pdf' ]
  - 'rtf': [ '.rtf' ]
  - 'odt': [ '.odt' ]
  - 'ods': [ '.ods' ]
  - 'odp': [ '.odp' ]
  - 'odg': [ '.odg' ]
  - 'epub': [ '.epub' ]
  - 'mobi': [ '.mobi' ]
  - 'pages': [ '.pages' ]
  - 'numbers': [ '.numbers' ]
  - 'keynote': [ '.key' ]
  - 'xps': [ '.xps' ]
  - 'djvu': [ '.djvu' ]

image_extensions_map:
  - 'raster': [ '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp', '.tiff', '.tif', '.ico', '.heic', '.heif' ]
  - 'vector': [ '.svg', '.eps', '.ai' ]
  - 'raw': [ '.raw', '.cr2', '.nef', '.arw', '.dng' ]
  - 'psd': [ '.psd', '.psb' ]

audio_extensions_map:
  - 'compressed': [ '.mp3', '.aac', '.ogg', '.wma', '.m4a', '.opus' ]
  - 'lossless': [ '.flac', '.wav', '.aiff', '.alac' ]
  - 'midi': [ '.mid', '.midi' ]

video_extensions_map:
  - 'common': [ '.mp4', '.mkv', '.avi', '.mov', '.wmv', '.flv', '.webm' ]
  - 'professional': [ '.mxf', '.prores' ]

archive_extensions_map:
  - 'compressed': [ '.zip', '.tar', '.gz', '.tgz', '.bz2', '.xz', '.7z', '.rar' ]
  - 'package': [ '.deb', '.rpm', '.dmg', '.pkg', '.msi', '.appimage' ]

data_extensions_map:
  - 'database': [ '.db', '.sqlite', '.sqlite3', '.mdb', '.accdb' ]
  - 'serialized': [ '.pickle', '.pkl', '.parquet', '.feather', '.arrow' ]
  - 'binary': [ '.bin', '.dat' ]

font_extensions_map:
  - 'font': [ '.ttf', '.otf', '.woff', '.woff2', '.eot' ]

model_extensions_map:
  - 'ml': [ '.pt', '.pth', '.onnx', '.h5', '.keras', '.pb', '.safetensors', '.gguf', '.ggml' ]
  - '3d': [ '.obj', '.fbx', '.gltf', '.glb', '.stl', '.blend' ]